---
#单机版
spring:
  application:
    name: ad-eureka
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#---
##server1
#spring:
#  application:
#    name: ad-eureka
#  profiles: server1
#server:
#  port: 8000
#eureka:
#  instance:
#    hostname: server1
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server2:8001/eureka/,http://server3:8002/eureka/
#
#---
##server2
#spring:
#  application:
#    name: ad-eureka
#  profiles: server2
#server:
#  port: 8001
#eureka:
#  instance:
#    hostname: server2
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server1:8000/eureka/,http://server3:8002/eureka/
#
#---
##server3
#spring:
#  application:
#    name: ad-eureka
#  profiles: server3
#server:
#  port: 8002
#eureka:
#  instance:
#    hostname: server3
#    prefer-ip-address: false
#  client:
#    service-url:
#      defaultZone: http://server1:8000/eureka/,http://server2:8001/eureka/
